'use strict';
/** Exact independent recurrence, native-word, and finite-block controls. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const o=require('../../operator_foundation/core/native_operator.cjs'),pmod=require('../../operator_foundation/core/paninian_operator.cjs'),s=require('./return_solver.cjs');
const {F,Cut,ONE,matrix:M,identity:I,zeros:Z,add,sub,scale,mul,equal,inverse,power,isZero}=o;
const checks=[],counts={coefficient_identities:0,finite_aperture_inverses:0,boundary_tests:0},data={};
function check(name,fn){fn();checks.push(name);}function eq(a,b){assert(equal(a,b));}function scalar(a,b){assert(F.of(a).eq(b));}
const R=M([[0,-1],[1,0]]),K=M([[0,1],[1,0]]),L=mul(K,R);
function chain(b,c,height){const n=2*(height+1),a=I(n),B=scale(R,b),C=scale(K,c);for(let j=0;j<height;j++)for(let r=0;r<2;r++)for(let t=0;t<2;t++){a[2*(j+1)+r][2*j+t]=B[r][t].neg();a[2*j+r][2*(j+1)+t]=C[r][t].neg();}return a;}
function corner(a){return a.slice(0,2).map(r=>r.slice(0,2));}
function determinant(a){a=M(a);let d=ONE;for(let j=0;j<a.length;j++){let k=j;while(k<a.length&&a[k][j].zero())k++;if(k===a.length)return new Cut();if(k!==j){[a[k],a[j]]=[a[j],a[k]];d=d.neg();}const pivot=a[j][j];d=d.mul(pivot);for(let i=j+1;i<a.length;i++){const q=a[i][j].div(pivot);for(let t=j;t<a.length;t++)a[i][t]=a[i][t].sub(q.mul(a[j][t]));}}return d;}
function continuant(q,k){q=F.of(q);if(k<2)return new F(1);let a=new F(1),b=new F(1);for(let j=2;j<=k;j++){[a,b]=[b,b.add(q.pow(2).mul(a))];}return b;}
function fullPresentation(){return new pmod.Presentation({tokens:[{name:'R',from:'*',to:'*',charge:0},{name:'K',from:'*',to:'*',charge:0},{name:'S',from:'*',to:'*',charge:1},{name:'T',from:'*',to:'*',charge:-1}],rules:[
 {id:'RR',lhs:['R','R'],rhs:[[[],-1]],source:'native EMK'}, {id:'KK',lhs:['K','K'],rhs:[[[],1]],source:'native EMK'},
 {id:'KR',lhs:['K','R'],rhs:[[['R','K'],-1]],source:'native EMK'},
 ...['S','T'].flatMap(x=>['R','K'].map(y=>({id:x+y,lhs:[x,y],rhs:[[[y,x],1]],source:'declared independent seam factor'}))),
 {id:'TS',lhs:['T','S'],rhs:[[[],1]],source:'declared return cancellation; ST is not identified with 1'}]});}
check('native_full_presentation_and_nonzero_aperture',()=>{const p=fullPresentation(),S=p.word(['S']),T=p.word(['T']),cut=p.one().minus(S.times(T));assert.equal(p.audit().status,'CONFLUENT_BY_CHECKED_DIAMONDS');assert(s.normal(cut).terms.size>0);assert(s.normal(cut.times(cut).minus(cut)).terms.size===0);assert(s.normal(cut.times(S)).terms.size===0);assert(s.normal(T.times(cut)).terms.size===0);assert(s.normal(S.times(T).minus(p.one())).terms.size>0);data.native_aperture={critical_pairs:p.audit().criticalPairs,nonzero:true,idempotent:true,ST_equals_one:false};});
check('scalar_Catalan_sequence',()=>assert.deepEqual(Array.from({length:8},(_,i)=>s.catalan(i).toString()),['1','1','2','5','14','42','132','429']));
check('all_order_formula_vs_native_recursion',()=>{for(const [b,c] of [[2,'3/5'],['1/2','3/4'],[1,2],[0,3]]){const m=s.gradedContract(b,c),coeff=s.firstReturnCoefficients(m.p,m.B,m.C,22);for(let n=0;n<coeff.length;n++){assert(coeff[n].equals(s.anticommutingCoefficient(m.p,m.witnesses.X,n)));counts.coefficient_identities++;}}});
check('direct_native_cut_powers_not_a_recurrence_assumption',()=>{const p=fullPresentation(),cut=p.one().minus(p.word(['S','T'])),H=p.word(['R','S'],2).plus(p.word(['K','T'],'3/5')),X=p.word(['K','R'],'6/5');let hn=p.one();for(let n=0;n<=20;n++){const actual=s.normal(cut.times(hn).times(cut)),expected=n%2===1?p.zero():s.normal(s.anticommutingCoefficient(p,X,n/2).times(cut));assert(actual.equals(expected));hn=s.normal(H.times(hn));}data.direct_native_powers=21;});
check('same_total_zero_retains_two_nonzero_history_tags',()=>{const m=s.gradedContract(2,'3/5'),nested=s.product(m.C,m.C,m.B,m.B),serial=s.product(m.C,m.B,m.C,m.B);assert(nested.terms.size&&serial.terms.size);assert(s.normal(nested.plus(serial)).terms.size===0);data.history_tags={nested:nested.toJSON(),serial:serial.toJSON(),sum_is_zero:true,individual_histories_erased:false};});
check('uncut_series_terms_do_not_tend_to_zero',()=>{const p=fullPresentation(),H=p.word(['R','S'],2).plus(p.word(['K','T'],'3/5'));let a=p.one();for(let n=1;n<=18;n++){a=s.normal(H.times(a));const top=a.entries().filter(([w])=>p.wordCharge(w)===BigInt(n));assert.equal(top.length,1);scalar(top[0][1].gauge(),new F(2).pow(n));assert(new F(2).pow(n).le(s.mass(a)));}data.uncut_growth_lower_bound='2^n';});
check('finite_even_apertures_direct_inverses_and_continuants',()=>{for(const [b,c] of [[2,'3/5'],[1,1],[3,1],['1/2',4],[0,3],[2,0]]){const q=F.of(b).mul(c);for(let k=0;k<=4;k++){const a=chain(b,c,2*k),inv=inverse(a),d=s.bracket(q,k).left;eq(corner(inv),add(I(2),scale(L,d)));eq(mul(a,inv),I(a.length));assert(determinant(a).eq(new Cut(continuant(q,k).pow(2))));counts.finite_aperture_inverses++;}}});
check('odd_aperture_can_fail_even_apertures_remain_valid',()=>{assert.throws(()=>inverse(chain(1,1,1)),/Singular/);eq(corner(inverse(chain(1,1,2))),add(I(2),L));data.odd_aperture_control={q:'1',height_one:'SINGULAR',height_two:'INVERTIBLE',all_even_heights:'PROVED_FOR_NONNEGATIVE_q'};});
check('continuant_and_Cassini_gap_without_sqrt',()=>{for(const q of ['0','1/10','1/2','6/5','3','10'])for(let k=1;k<=35;k++){const r=s.bracket(q,k),pk=continuant(q,k),pk1=continuant(q,k+1);scalar(r.left,F.of(q).mul(continuant(q,k-1)).div(pk));scalar(r.width,F.of(q).pow(2*k+1).div(pk.mul(pk1)));}});
check('nested_intervals_for_large_and_small_couplings',()=>{for(const q of ['0','1/8','1/2','1','6/5','10','100']){let prior=s.bracket(q,0);for(let k=1;k<=90;k++){const r=s.bracket(q,k);assert(prior.lower.le(r.lower)&&r.upper.le(prior.upper));prior=r;}}});
check('all_nonnegative_boundary_seeds_are_sandwiched',()=>{for(const q of ['1/8','6/5','10'])for(const seed of ['0','1/7','1','1000'])for(let k=1;k<=20;k++){const value=s.continueFrom(q,seed,k),r=s.bracket(q,k-1);assert(r.lower.le(value)&&value.le(r.upper));counts.boundary_tests++;}});
check('rational_roots_recognized_beyond_power_series_radius',()=>{for(const d of ['1/3','1/2','2/3','9/10']){const f=F.of(d),q=f.div(new F(1).sub(f.pow(2)));assert(s.checkRationalRoot(q,d));const r=s.bracket(q,55);assert(r.lower.le(f)&&f.le(r.upper));}assert(!s.checkRationalRoot('6/5','1/3'));});
check('main_response_exact_enclosure_and_error',()=>{const r=s.solve(),d=new F(2,3);assert.equal(r.status,'CERTIFIED_RECOGNITION_RESPONSE');assert(d.sub(r.bracket.estimate).abs().le(r.bracket.error));assert(r.bracket.error.le('1/1000000000000'));assert(s.checkRationalRoot('6/5','2/3'));data.main={q:r.q,exact_d:'2/3',exact_response:'I+(2/3)KR',normal_response:'I-(2/3)RK',maximum_aperture_height:Math.max(...r.bracket.aperture_heights),refinements:r.bracket.depth,error_bound:r.bracket.error.toString(),all_three_strict_series_gates_fail:Object.values(r.series_comparison).every(x=>x===false)};assert(data.main.all_three_strict_series_gates_fail);});
check('return_series_itself_diverges_in_main_case',()=>{const q=new F(6,5);let last=new F(0);for(let n=0;n<20;n++){const term=s.catalan(n).mul(q.pow(2*n+1));assert(last.le(term));last=term;}assert(new F(1000000).le(last));data.return_series_radius_in_q='1/2';});
check('native_quadratic_closes_without_fitting',()=>{const m=s.gradedContract(2,'3/5'),f=m.p.one().plus(m.L.scale('2/3'));assert(s.normal(f.minus(m.p.one()).minus(s.product(m.C,f,m.B,f))).terms.size===0);});
check('wrong_commuting_shortcut_changes_coefficients',()=>{const m=s.gradedContract(2,'3/5'),a=s.firstReturnCoefficients(m.p,m.B,m.C,2);assert.equal(a[2].terms.size,0);assert(s.product(m.witnesses.X,m.witnesses.X).scale(2).terms.size>0);assert.throws(()=>s.certifyRelations(m.p,m.B,m.p.one()),/does not close/);});
check('scalarized_positive_feedback_has_no_real_fixedpoint',()=>{const q=new F(6,5);assert(new F(1).sub(q.mul(4)).n<0n);data.commuting_control={law:'f=1+q f^2',q:'6/5',real_discriminant:'-19/5',real_finite_solution:false};});
check('exact_zero_coupling_and_budget_fail_closed',()=>{assert.equal(s.solve({opening:0,closing:3}).status,'CERTIFIED_RECOGNITION_RESPONSE');assert.equal(s.solve({maxRefinements:1}).status,'REFINEMENT_BUDGET_EXHAUSTED');assert.throws(()=>s.solve({opening:-1}),RangeError);assert.throws(()=>s.solve({tolerance:0}),RangeError);assert.throws(()=>s.solve({closing:0.1}),TypeError);assert.throws(()=>s.iterate(1,-1),RangeError);});
check('small_coupling_absolute_tail_does_not_claim_large_coupling',()=>{const m=s.gradedContract(2,'3/16');assert.equal(s.pairedTail(m.p,m.witnesses.X,10).status,'CERTIFIED_ABSOLUTE_TAIL');const big=s.gradedContract(2,'3/5');assert.equal(s.pairedTail(big.p,big.witnesses.X,10).status,'OUTSIDE_STRICT_RETURN_SERIES_GATE');});
check('amplitude_imbalance_is_still_unseen_by_this_target',()=>{const a=s.solve({opening:2,closing:'3/5'}),b=s.solve({opening:20,closing:'3/50'});assert.equal(a.q,b.q);assert.deepEqual(a.response,b.response);data.target_boundary='Same bc gives same return response; full source amplitudes are not reconstructed.';});
check('quantified_joint_cutoff_coupling_limit',()=>{for(const q of ['1/10','1','6/5','3','10','100'])for(let k=1;k<=45;k++){const r=s.bracket(q,k),bound=s.emergentCutBound(q,k);assert(r.left.sub(1).abs().div(2).le(bound.toStrongCouplingAperture));}data.emergent_cut={selected_aperture:'(I+KR)/2',joint_error_bound:'q/k+1/(4q)',required_joint_limit:'q -> infinity and k/q -> infinity',hilbert_or_physical_time_premise:false};});
check('coupling_and_aperture_limits_cannot_be_swapped',()=>{const q=new F(1000),even=s.bracket(q,2).left,odd=s.bracket(q,3).left;assert(even.le('1/100'));assert(new F(400).le(odd));data.limit_order_control={q:'1000',k_2_response:even.toString(),k_3_response:odd.toString(),fixed_aperture_strong_coupling_not_the_same_limit:true};});
check('limiting_approximate_cut_defect_is_quantified',()=>{const d=new F(2,3),q=new F(6,5),cut=scale(add(I(2),scale(L,d)),'1/2');eq(sub(mul(cut,cut),cut),scale(I(2),d.div(q.mul(4)).neg()));});
check('primitive_witness_replay_is_presentation_bound',()=>{const m=s.gradedContract(2,'3/5');assert(m.p.replay(m.witnesses.anticommutator));assert(m.p.replay(m.witnesses.cutSquare));assert(m.p.replay(m.witnesses.feedback));const bad=JSON.parse(JSON.stringify(m.witnesses.cutSquare));bad.presentation='wrong';assert.throws(()=>m.p.replay(bad),/Wrong/);});
const root=__dirname,inputs=['return_solver.cjs','verify.cjs','mutate.cjs','THEOREM.md','README.md','LINEAGE.json','../../operator_foundation/core/native_operator.cjs','../../operator_foundation/core/paninian_operator.cjs'];
const hashes=Object.fromEntries(inputs.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));
const result={protocol:'RKF_NATIVE_GRADED_APERTURE_EXPERIMENT_R1',status:'PASS_EXACT_FINITE_CHECKS',runtime:process.version,check_count:checks.length,checks,counts,results:data,source_sha256:hashes,scope:{general_theorems:'THEOREM.md',primitive_hilbert_space:false,exact_finite_tests_are_not_universal_proofs:true,global_inverse_status:'NOT_CLAIMED_OR_TESTED_IN_THE_INFINITE_COMPLETION',new_external_priority_established:false,physical_quantum_gravity_established:false}};
const text=JSON.stringify(result,null,2)+'\n',hash=crypto.createHash('sha256').update(text).digest('hex'),file=path.join(root,'RESULT.json'),pin=path.join(root,'EXPECTED.sha256');
if(process.argv.includes('--write')){fs.writeFileSync(file,text);fs.writeFileSync(pin,hash+'\n');}else if(process.argv.includes('--check')){assert.equal(fs.readFileSync(file,'utf8'),text,'Source/evidence drift');assert.equal(fs.readFileSync(pin,'utf8').trim(),hash,'Pin mismatch');}
console.log(JSON.stringify({protocol:result.protocol,status:result.status,check_count:checks.length,counts,main:data.main,certificate_sha256:hash},null,2));
