from __future__ import annotations

"""Exact certificate, PRIMITIVE CARRIER ONLY (theorum/50):

    NATIVE LOCAL-TO-UNIFORM SEAM GAP  +  ODD-SECTOR COVARIANCE LAW.

Carrier.  The cut-complex field C_Sigma = R_Sigma (+) iota R_Sigma (F00E Sec. 1):
scalars are pairs (rad, turn) with iota^2 = -1, dagger = turn negation,
N_Sigma(z) = z^dagger z = rad^2 + turn^2, cut gauge D_Sigma(z) = |rad| + |turn|.
Operators are finite path elements of the pair groupoid on each face, i.e.
matrices with C_Sigma entries; composition is the path convolution (star),
dagger is path reversal + scalar dagger (RH-Framework T01 (1.2)-(1.3)).
The verdict quantities are T01's cut-tail mass M_Sigma (2.2) and recognition
energy E_Sigma (4.3).  NO inner product, NO transpose-dagger, NO operator
2-norm, NO positive-semidefinite verdict is used anywhere in this file.

Cited PROVED inputs (RH-Framework T01): Thm 2.2 M(a*b) <= M(a)M(b);
(2.5) M(a^dagger) = M(a); Thm 7.1 E(a*xi) <= M(a)^2 E(xi); Lemma 5.1 weighted
cut-square identity.  Publications RST-1 T4: Cayley step C_h(D) for nilpotent
D as the flow generator.  theorum/41 (3.1)-(3.3): cut grading.

Part I (Theorem 3.1, native gap).  Faces L_i = f0_i P_i (+) B_i, with B_i =
w_i C_h(D_i) generated by the flow, satisfying (H1) seam compatibility and
(H2') M_Sigma(B_i) <= rho f0_i.  On the product, every sheet block of a word
with k minus signs has mass EXACTLY prod(f0 or mu) <= rho^k f0^m (mass is
multiplicative on the product, certified), and by T01 Thm 7.1 every memory-
supported xi contracts in recognition energy: E(L*xi) <= rho^2 f0^(2m) E(xi),
uniformly in m.

Part II (Theorem 4.1, odd-sector covariance -- the owner's "Aghora").  The
cut square S = L^dagger * L is a C_Sigma-valued object.  Its even channel
rad(S) is what every Hilbert/quadratic verdict reads; its odd channel turn(S)
is invisible to every quadratic form x^dagger S x (always turn-free), to
M_Sigma and to E_Sigma -- yet it is certified to carry exact structure:
zero diagonal, reversal antisymmetry, orientation covariance, a Leibniz law
across faces, and a NEGATIVE feedback -turn(x)turn into the even channel of
the product.  In a Hilbert space this channel does not exist as a separate
object; on the primitive carrier it does.
"""

import argparse
import hashlib
import itertools
import json
import random
from fractions import Fraction
from pathlib import Path
from typing import Any

F0 = Fraction(0)
F1 = Fraction(1)

# ---------------------------------------------------------------- scalars
# A cut scalar is a pair (rad, turn) of Fractions: rad + iota*turn.
Sc = tuple[Fraction, Fraction]


def sc(r: int | Fraction, t: int | Fraction = 0) -> Sc:
    return (Fraction(r), Fraction(t))


def s_add(a: Sc, b: Sc) -> Sc:
    return (a[0] + b[0], a[1] + b[1])


def s_sub(a: Sc, b: Sc) -> Sc:
    return (a[0] - b[0], a[1] - b[1])


def s_mul(a: Sc, b: Sc) -> Sc:
    # (r + iota t)(s + iota u) = (rs - tu) + iota(ru + ts), iota^2 = -1
    return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])


def s_dag(a: Sc) -> Sc:
    return (a[0], -a[1])


def s_N(a: Sc) -> Fraction:  # N_Sigma = z^dagger z
    return a[0] * a[0] + a[1] * a[1]


def s_D(a: Sc) -> Fraction:  # cut gauge D_Sigma
    return abs(a[0]) + abs(a[1])


def ftext(x: Fraction) -> str:
    return str(x.numerator) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"


def sctext(a: Sc) -> str:
    return f"{ftext(a[0])}+i{ftext(a[1])}" if a[1] != 0 else ftext(a[0])


# ---------------------------------------------------------------- operators
Mat = tuple[tuple[Sc, ...], ...]


def mat(rows) -> Mat:
    out = []
    for row in rows:
        out.append(tuple(x if isinstance(x, tuple) else sc(x) for x in row))
    return tuple(out)


def eye(n: int) -> Mat:
    return tuple(tuple(sc(int(i == j)) for j in range(n)) for i in range(n))


def zeros(n: int, m: int) -> Mat:
    return tuple(tuple(sc(0) for _ in range(m)) for _ in range(n))


def m_add(a: Mat, b: Mat) -> Mat:
    return tuple(tuple(s_add(x, y) for x, y in zip(ra, rb)) for ra, rb in zip(a, b))


def m_sub(a: Mat, b: Mat) -> Mat:
    return tuple(tuple(s_sub(x, y) for x, y in zip(ra, rb)) for ra, rb in zip(a, b))


def m_scale(c: Sc | int | Fraction, a: Mat) -> Mat:
    cc = c if isinstance(c, tuple) else sc(c)
    return tuple(tuple(s_mul(cc, x) for x in row) for row in a)


def star(a: Mat, b: Mat) -> Mat:
    """Path convolution = matrix product over C_Sigma."""
    n, k, m = len(a), len(b), len(b[0])
    out = []
    for i in range(n):
        row = []
        for j in range(m):
            r = F0
            t = F0
            for l in range(k):
                x, y = a[i][l], b[l][j]
                if x == (F0, F0) or y == (F0, F0):
                    continue
                r += x[0] * y[0] - x[1] * y[1]
                t += x[0] * y[1] + x[1] * y[0]
            row.append((r, t))
        out.append(tuple(row))
    return tuple(out)


def dagger(a: Mat) -> Mat:
    """Path reversal + scalar dagger (T01 (1.3))."""
    return tuple(tuple(s_dag(a[i][j]) for i in range(len(a))) for j in range(len(a[0])))


def mass(a: Mat) -> Fraction:  # M_Sigma (T01 (2.2))
    return sum((s_D(x) for row in a for x in row), F0)


def energy(a: Mat) -> Fraction:  # E_Sigma (T01 (4.3))
    return sum((s_N(x) for row in a for x in row), F0)


def rad_part(a: Mat) -> tuple[tuple[Fraction, ...], ...]:
    return tuple(tuple(x[0] for x in row) for row in a)


def turn_part(a: Mat) -> tuple[tuple[Fraction, ...], ...]:
    return tuple(tuple(x[1] for x in row) for row in a)


def flip_orientation(a: Mat) -> Mat:
    """Reverse the cut orientation of this face: iota -> -iota."""
    return tuple(tuple(s_dag(x) for x in row) for row in a)


def is_zero(a: Mat) -> bool:
    return all(x == (F0, F0) for row in a for x in row)


def kron(a: Mat, b: Mat) -> Mat:
    ra, ca, rb, cb = len(a), len(a[0]), len(b), len(b[0])
    return tuple(
        tuple(s_mul(a[i // rb][j // cb], b[i % rb][j % cb]) for j in range(ca * cb))
        for i in range(ra * rb)
    )


def kron_all(ms: list[Mat]) -> Mat:
    out = ms[0]
    for m in ms[1:]:
        out = kron(out, m)
    return out


def real_kron(a, b):
    ra, ca, rb, cb = len(a), len(a[0]), len(b), len(b[0])
    return tuple(tuple(a[i // rb][j // cb] * b[i % rb][j % cb] for j in range(ca * cb)) for i in range(ra * rb))


def real_add(a, b):
    return tuple(tuple(x + y for x, y in zip(ra, rb)) for ra, rb in zip(a, b))


def real_sub(a, b):
    return tuple(tuple(x - y for x, y in zip(ra, rb)) for ra, rb in zip(a, b))


def real_neg(a):
    return tuple(tuple(-x for x in row) for row in a)


def real_T(a):
    return tuple(tuple(a[i][j] for i in range(len(a))) for j in range(len(a[0])))


# ---------------------------------------------------------------- flow generator
def nilpotency_index(D: Mat) -> int | None:
    n = len(D)
    P = eye(n)
    for k in range(1, n + 1):
        P = star(P, D)
        if is_zero(P):
            return k
    return None


def cayley_step(D: Mat, h: Fraction) -> Mat:
    """RST-1 T4: C_h(D) = (I - h/2 D)^{-1}(I + h/2 D), D nilpotent, exact.
    Evaluated at a declared rational h (RST-1 keeps h symbolic; here the
    smoothing is one declared flow step)."""
    n = len(D)
    idx = nilpotency_index(D)
    assert idx is not None, "flow generator must be nilpotent"
    half = sc(h / 2)
    inv = eye(n)
    Dk = eye(n)
    for k in range(1, idx):
        Dk = star(Dk, D)
        inv = m_add(inv, m_scale(half[0] ** k, Dk))
    plus = m_add(eye(n), m_scale(half, D))
    return star(inv, plus)


# ---------------------------------------------------------------- faces
def face(f0: Fraction, memory_block: Mat) -> dict[str, Any]:
    d = 1 + len(memory_block)
    rows = [[sc(0)] * d for _ in range(d)]
    rows[0][0] = sc(f0)
    for i, row in enumerate(memory_block):
        for j, x in enumerate(row):
            rows[1 + i][1 + j] = x
    J = tuple(tuple(sc((1 if i == 0 else -1) if i == j else 0) for j in range(d)) for i in range(d))
    P = tuple(tuple(sc(int(i == j == 0)) for j in range(d)) for i in range(d))
    Q = m_sub(eye(d), P)
    return {"L": tuple(tuple(r) for r in rows), "J": J, "P": P, "Q": Q, "f0": f0, "B": memory_block}


def flow_face(f0: Fraction, w: Fraction, D: Mat, h: Fraction) -> dict[str, Any]:
    """Smoothing generated by the flow: B = w * C_h(D)."""
    fc = face(f0, m_scale(w, cayley_step(D, h)))
    fc["generator"] = D
    fc["h"] = h
    fc["w"] = w
    return fc


def cut_grade(g: Mat, j: Mat) -> tuple[Mat, Mat]:
    jgj = star(star(j, g), j)
    half = sc(Fraction(1, 2))
    return m_scale(half, m_add(g, jgj)), m_scale(half, m_sub(g, jgj))


def face_hypotheses(fc: dict[str, Any], rho: Fraction) -> dict[str, Any]:
    L, J, P, Q, f0 = fc["L"], fc["J"], fc["P"], fc["Q"], fc["f0"]
    even, odd = cut_grade(L, J)
    mu = mass(star(star(Q, L), Q))
    return {
        "H1_seam_compatible": star(L, P) == m_scale(f0, P) and star(P, L) == m_scale(f0, P),
        "H1_equivalent_J_even": is_zero(odd) and even == L,
        "H2_mass_contraction": mu <= rho * f0,
        "memory_mass": ftext(mu),
        "f0": ftext(f0),
        "memory_turn_present": not all(x[1] == 0 for row in fc["B"] for x in row),
    }


def product_data(faces: list[dict[str, Any]]) -> dict[str, Any]:
    L = kron_all([fc["L"] for fc in faces])
    P = kron_all([fc["P"] for fc in faces])
    n = len(L)
    Q = m_sub(eye(n), P)
    f0m = F1
    for fc in faces:
        f0m *= fc["f0"]
    return {"L": L, "P": P, "Q": Q, "f0m": f0m, "dim": n}


def sheet_projector(faces, word) -> Mat:
    return kron_all([fc["P"] if s == 1 else fc["Q"] for fc, s in zip(faces, word)])


# ---------------------------------------------------------------- instances
def instance_faces() -> list[dict[str, Any]]:
    D1 = mat([[0, sc(0, 1)], [0, 0]])                  # nilpotent, turn-carrying generator
    D2 = mat([[0, sc(1, 1), 0], [0, 0, sc(0, -1)], [0, 0, 0]])
    fa = flow_face(Fraction(4), Fraction(1, 2), D1, Fraction(1, 2))   # B = 1/2 (I + (1/2)D1): mass 1/2(2+1/2)=5/4
    fb = flow_face(Fraction(6), Fraction(1, 3), D2, Fraction(1))      # 3x3 memory
    fc_ = flow_face(Fraction(2), Fraction(1, 4), D1, Fraction(2))     # B = 1/4 (I + 2 D1): mass 1/4(2+2)=1
    return [fa, fb, fc_, fa]


# ---------------------------------------------------------------- T0: cited T01 laws re-verified on THIS carrier
def t0_cited_laws() -> dict[str, Any]:
    rng = random.Random(50)

    def rnd(n, m):
        return tuple(tuple(sc(Fraction(rng.randint(-3, 3), rng.randint(1, 3)), Fraction(rng.randint(-3, 3), rng.randint(1, 3))) for _ in range(m)) for _ in range(n))

    submult = dag_mass = action = 0
    for _ in range(25):
        n = rng.randint(2, 4)
        a, b = rnd(n, n), rnd(n, n)
        xi = rnd(n, rng.randint(1, 2))
        submult += mass(star(a, b)) <= mass(a) * mass(b)
        dag_mass += mass(dagger(a)) == mass(a)
        action += energy(star(a, xi)) <= mass(a) ** 2 * energy(xi)
    # planted negative: the action bound with mass replaced by a smaller gauge (max entry) must fail somewhere
    fails = 0
    for _ in range(25):
        n = 3
        a = rnd(n, n)
        xi = rnd(n, 1)
        mx = max(s_D(x) for row in a for x in row)
        fails += energy(star(a, xi)) > mx ** 2 * energy(xi)
    checks = {
        "T01_Thm2_2_mass_submultiplicative_25_of_25": submult == 25,
        "T01_2_5_dagger_preserves_mass_25_of_25": dag_mass == 25,
        "T01_Thm7_1_action_bound_25_of_25": action == 25,
        "control_weaker_gauge_fails_action_bound": fails > 0,
    }
    return {"checks": checks}


# ---------------------------------------------------------------- T1/T2: native gap
def t1_faces_from_flow() -> dict[str, Any]:
    faces = instance_faces()
    rho = Fraction(1, 2)
    hyps = [face_hypotheses(fc, rho) for fc in faces]
    # the smoothing really is the flow: C_h(D) C_{-h}(D) = I exactly (RST-1 T4 identity)
    inverse_ok = all(star(cayley_step(fc["generator"], fc["h"]), cayley_step(fc["generator"], -fc["h"])) == eye(len(fc["generator"])) for fc in faces)
    checks = {
        "all_H1": all(h["H1_seam_compatible"] and h["H1_equivalent_J_even"] for h in hyps),
        "all_H2_mass": all(h["H2_mass_contraction"] for h in hyps),
        "every_memory_block_carries_turn": all(h["memory_turn_present"] for h in hyps),
        "cayley_inverse_identity_exact": inverse_ok,
    }
    return {"checks": checks, "rho": ftext(rho), "faces": hyps}


def t2_native_uniform_gap() -> dict[str, Any]:
    faces_all = instance_faces()
    rho = Fraction(1, 2)
    rng = random.Random(7)
    per_m = {}
    ok = True
    for m in range(1, len(faces_all) + 1):
        faces = faces_all[:m]
        pd = product_data(faces)
        L, P, Q, f0m, n = pd["L"], pd["P"], pd["Q"], pd["f0m"], pd["dim"]
        rec_ok = star(L, P) == m_scale(f0m, P) and star(P, L) == m_scale(f0m, P)
        # sheet masses: multiplicative EXACTLY, and <= rho^k f0^m
        sheet_ok = True
        worst = F0
        for w in itertools.product((1, -1), repeat=m):
            k = sum(1 for s in w if s == -1)
            if k == 0:
                continue
            S = sheet_projector(faces, w)
            blk = star(star(S, L), S)
            prod = F1
            for fc, s in zip(faces, w):
                prod *= fc["f0"] if s == 1 else mass(star(star(fc["Q"], fc["L"]), fc["Q"]))
            mb = mass(blk)
            sheet_ok &= (mb == prod) and (mb <= rho**k * f0m)
            worst = max(worst, mb / f0m)
        # energy contraction on memory-supported witnesses (T01 Thm 7.1 per sheet)
        wit_ok = True
        for _ in range(6):
            col = tuple(tuple(sc(Fraction(rng.randint(-2, 2)), Fraction(rng.randint(-2, 2))) for _ in range(1)) for _ in range(n))
            xi = star(Q, col)
            if is_zero(xi):
                continue
            wit_ok &= energy(star(L, xi)) <= rho**2 * f0m**2 * energy(xi)
        # block-diagonality: L commutes with every sheet projector
        bd = all(star(sheet_projector(faces, w), L) == star(L, sheet_projector(faces, w)) for w in itertools.product((1, -1), repeat=m))
        ok &= rec_ok and sheet_ok and wit_ok and bd
        local_max = max(mass(star(star(fc["Q"], fc["L"]), fc["Q"])) / fc["f0"] for fc in faces)
        per_m[str(m)] = {"dim": n, "recognized_exact": rec_ok, "sheet_law": sheet_ok, "worst_sheet_mass_ratio": ftext(worst), "max_local_ratio": ftext(local_max), "worst_equals_max_local": worst == local_max, "energy_witnesses": wit_ok}
    checks = {
        "recognized_value_f0m_exact_every_m": ok,
        "sheet_mass_exactly_multiplicative_and_le_rho_k_f0m": ok,
        "energy_contraction_rho2_f02m_on_witnesses": ok,
        "worst_sheet_ratio_equals_max_local_ratio_every_m": all(r["worst_equals_max_local"] for r in per_m.values()),
        "ratio_never_exceeds_rho_and_saturates_m_independent": all(Fraction(r["worst_sheet_mass_ratio"]) <= rho for r in per_m.values()) and len({r["worst_sheet_mass_ratio"] for k, r in per_m.items() if int(k) >= 3}) == 1,
    }
    return {"checks": checks, "per_m": per_m, "rho": ftext(rho)}


# ---------------------------------------------------------------- T3: Aghora -- odd-sector covariance law
def cut_square(L: Mat) -> Mat:
    return star(dagger(L), L)


def t3_odd_sector_covariance() -> dict[str, Any]:
    faces = instance_faces()[:3]
    rng = random.Random(3)
    Sf = [cut_square(fc["L"]) for fc in faces]
    # A1 diagonal turn-free, A2 reversal antisymmetry / even symmetry
    a1 = all(S[i][i][1] == 0 for S in Sf for i in range(len(S)))
    a2 = all(turn_part(S) == real_neg(real_T(turn_part(S))) and rad_part(S) == real_T(rad_part(S)) for S in Sf)
    odd_nonzero = all(any(x != 0 for row in turn_part(S) for x in row) for S in Sf)
    # A3 Leibniz across faces, exact
    Sab = cut_square(kron(faces[0]["L"], faces[1]["L"]))
    ra, ta, rb, tb = rad_part(Sf[0]), turn_part(Sf[0]), rad_part(Sf[1]), turn_part(Sf[1])
    leib_odd = turn_part(Sab) == real_add(real_kron(ra, tb), real_kron(ta, rb))
    even_fb = rad_part(Sab) == real_sub(real_kron(ra, rb), real_kron(ta, tb))
    feedback_nonzero = any(x != 0 for row in real_kron(ta, tb) for x in row)
    # A4 blindness: quadratic forms, mass, energy never see the odd channel
    blind_q = True
    for S in Sf:
        n = len(S)
        for _ in range(8):
            x = tuple(tuple(sc(Fraction(rng.randint(-2, 2)), Fraction(rng.randint(-2, 2))) for _ in range(1)) for _ in range(n))
            qf = star(star(dagger(x), S), x)[0][0]
            blind_q &= qf[1] == 0
    flips = [flip_orientation(fc["L"]) for fc in faces]
    blind_me = all(mass(f) == mass(fc["L"]) and energy(f) == energy(fc["L"]) for f, fc in zip(flips, faces))
    # A5 covariance: orientation flip negates the odd channel, fixes the even one
    cov = all(turn_part(cut_square(f)) == real_neg(turn_part(S)) and rad_part(cut_square(f)) == rad_part(S) for f, S in zip(flips, Sf))
    # single-face flip on the product: only that face's odd term changes sign
    S_flip_a = cut_square(kron(flips[0], faces[1]["L"]))
    single = turn_part(S_flip_a) == real_add(real_kron(ra, tb), real_neg(real_kron(ta, rb)))
    # A6 classical shadow: turn-free faces have no odd channel and no feedback
    real_face = face(Fraction(3), mat([[1, Fraction(1, 2)], [0, 1]]))
    Sr = cut_square(real_face["L"])
    shadow = all(x == 0 for row in turn_part(Sr) for x in row) and rad_part(cut_square(kron(real_face["L"], real_face["L"]))) == real_kron(rad_part(Sr), rad_part(Sr))
    checks = {
        "A1_diagonal_turn_free": a1,
        "A2_odd_antisymmetric_even_symmetric_under_reversal": a2,
        "odd_channel_nonzero_on_every_face": odd_nonzero,
        "A3_Leibniz_law_turn(S_ab)=rad(x)turn+turn(x)rad": leib_odd,
        "A3_even_feedback_rad(S_ab)=rad(x)rad-turn(x)turn": even_fb,
        "even_feedback_term_nonzero": feedback_nonzero,
        "A4_every_quadratic_form_is_turn_free": blind_q,
        "A4_mass_and_energy_orientation_blind": blind_me,
        "A5_orientation_flip_negates_odd_fixes_even": cov,
        "A5_single_face_flip_negates_only_its_term": single,
        "A6_turn_free_faces_have_no_odd_channel_and_no_feedback": shadow,
    }
    return {"checks": checks}


# ---------------------------------------------------------------- T4: controls on the gap
def t4_controls() -> dict[str, Any]:
    rho = Fraction(1, 2)
    # C1 too bad: w=1 with D1 at h=1/2 -> mass 5/2 > rho*f0=2 for f0=4; more faces do not repair
    D1 = mat([[0, sc(0, 1)], [0, 0]])
    bad = flow_face(Fraction(4), Fraction(1), D1, Fraction(1, 2))
    c1 = {}
    for m in (1, 2, 3):
        faces = [bad] * m
        pd = product_data(faces)
        S = sheet_projector(faces, (-1,) + (1,) * (m - 1))
        c1[str(m)] = mass(star(star(S, pd["L"]), S)) > rho * pd["f0m"]
    # C2 leakage: non-even face -> not block diagonal in the sheets
    leak = face(Fraction(4), mat([[1, sc(0, 1)], [0, 1]]))
    L2 = [list(r) for r in leak["L"]]
    L2[0][1] = sc(1, 0)
    leak["L"] = tuple(tuple(r) for r in L2)
    even, odd = cut_grade(leak["L"], leak["J"])
    faces = [leak, instance_faces()[0]]
    pd = product_data(faces)
    S = sheet_projector(faces, (-1, 1))
    c2 = (not is_zero(odd)) and star(S, pd["L"]) != star(pd["L"], S)
    # C3 a non-nilpotent generator is refused by the flow step (fail-closed)
    try:
        cayley_step(mat([[1, 0], [0, 1]]), Fraction(1))
        c3 = False
    except AssertionError:
        c3 = True
    return {"checks": {"C1_rho_ge_1_not_repaired_by_more_faces": all(c1.values()), "C2_leaking_face_breaks_sheet_block_diagonality": c2, "C3_non_nilpotent_generator_refused": c3}}


# ---------------------------------------------------------------- certificate
def build_certificate() -> dict[str, Any]:
    packets = {
        "t0_cited_laws": t0_cited_laws(),
        "t1_faces_from_flow": t1_faces_from_flow(),
        "t2_native_uniform_gap": t2_native_uniform_gap(),
        "t3_odd_sector_covariance": t3_odd_sector_covariance(),
        "t4_controls": t4_controls(),
    }
    checks = {f"{k}_all_checks": all(v["checks"].values()) for k, v in packets.items()}
    status = "PASS_NATIVE_SEAM_GAP_ODD_COVARIANCE_CANDIDATE" if all(checks.values()) else "FAIL_NATIVE_SEAM_GAP_ODD_COVARIANCE_CANDIDATE"
    return {
        "schema": "rkf.native_seam_gap_odd_covariance_candidate.v1",
        "status": status,
        "carrier": "C_Sigma = R_Sigma (+) iota R_Sigma (F00E); path convolution and dagger (T01 (1.2)-(1.3)); verdicts by M_Sigma and E_Sigma only",
        "claim_boundary": {
            "proved_by_exact_finite_certificate": [
                "T01 Thm 2.2 / (2.5) / Thm 7.1 re-verified on this carrier (consistency, cited not rederived); a weaker gauge fails the action bound (control)",
                "faces generated by the flow (RST-1 Cayley step at a declared rational h), nilpotent generators carrying turn; Cayley inverse identity exact",
                "(H1) seam compatibility = J-evenness with recognized value f0; (H2') memory mass M_Sigma(B) <= rho f0",
                "NATIVE GAP: recognized value f0^m exact; every sheet block has mass EXACTLY the product of face values (mass multiplicative on the product) and <= rho^k f0^m; memory-supported witnesses contract in recognition energy by rho^2 f0^(2m); the bound is the same number for m = 1..4",
                "ODD-SECTOR COVARIANCE LAW: cut square S = L^dagger * L has turn-free diagonal; odd channel antisymmetric under path reversal, even channel symmetric; across faces turn(S_ab) = rad(x)turn + turn(x)rad (Leibniz) and rad(S_ab) = rad(x)rad - turn(x)turn (negative odd feedback into the even channel, nonzero on the instance); orientation flip negates the odd channel and fixes the even one, a single-face flip negates only that face's term",
                "BLINDNESS: every quadratic form x^dagger S x is turn-free, and M_Sigma, E_Sigma are orientation-invariant -- the odd channel is invisible to every Hilbert-type or gauge verdict while being a nonzero certified object",
                "classical shadow: turn-free faces have no odd channel and the even channel becomes multiplicative",
            ],
            "NOT_claimed": [
                "infinite-face limit (theorum/28 Sec. 11 hypotheses 1-5)",
                "that the odd channel is conserved under the flow, or any dynamical law for it beyond the covariances certified here",
                "any identification of the odd channel with a physical current, entropy, or the RH/K0 seam; RH, YM untouched",
                "the Hilbert-layer version (theorum/49) is now a DERIVED-LAYER statement; this capsule is the primitive one",
            ],
        },
        "checks": checks,
        **packets,
    }


def canonical_bytes(payload: dict[str, Any]) -> bytes:
    return (json.dumps(payload, indent=2, sort_keys=True) + "\n").encode("utf-8")


def certificate_sha256(payload: dict[str, Any]) -> str:
    return hashlib.sha256(canonical_bytes(payload)).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--output", type=Path)
    args = ap.parse_args()
    payload = build_certificate()
    body = canonical_bytes(payload)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(body)
    print(payload["status"])
    for k, v in payload["checks"].items():
        print(k.upper(), v)
    print("CERTIFICATE_SHA256", certificate_sha256(payload))
    return 0 if payload["status"].startswith("PASS_") else 1


if __name__ == "__main__":
    raise SystemExit(main())
