'use strict';
/** Independent finite block inverses, symbolic witnesses and exact tail tests.
 * Infinite-profile conclusions live in THEOREM.md, not in a finite test count.
 */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const o=require('../../../operator_foundation/core/native_operator.cjs'),s=require('./variable_return.cjs'),r1=require('../return_solver.cjs');
const {F,Cut,ONE,matrix:M,identity:I,zeros:Z,add,sub,scale,mul,equal,inverse}=o;
function rounded(x,up=true){x=F.of(x);const d=1000000000000n,n=x.n*d;return new F(up?(n+x.d-1n)/x.d:n/x.d,d);}
const checks=[],counts={direct_full_inverses:0,local_pair_inverses:0,tail_enclosures:0,periodic_targets:0},results={};
function check(name,f){f();checks.push(name);}function eq(a,b){assert(equal(a,b));}function num(a,b){assert(F.of(a).eq(b));}
const R=M([[0,-1],[1,0]]),K=M([[0,1],[1,0]]),L=mul(K,R);
function bondsFor(xs,variant=0){return xs.flatMap((q,j)=>[0,1].map(k=>{const b=new F(variant===0?2:j+k+1,variant===0?1:k+1);return {opening:b,closing:F.of(q).div(b)};}));}
function fullChain(bonds){const a=I(2*(bonds.length+1));bonds.forEach((e,j)=>{const B=scale(R,e.opening),C=scale(K,e.closing);for(let r=0;r<2;r++)for(let c=0;c<2;c++){a[2*j+r][2*j+2+c]=C[r][c].neg();a[2*j+2+r][2*j+c]=B[r][c].neg();}});return a;}
function corner(a){return a.slice(0,2).map(x=>x.slice(0,2));}
function determinant(a){a=M(a);let d=ONE;for(let j=0;j<a.length;j++){let k=j;while(k<a.length&&a[k][j].zero())k++;if(k===a.length)return new Cut();if(k!==j){[a[k],a[j]]=[a[j],a[k]];d=d.neg();}const p=a[j][j];d=d.mul(p);for(let i=j+1;i<a.length;i++){const q=a[i][j].div(p);for(let t=j;t<a.length;t++)a[i][t]=a[i][t].sub(q.mul(a[j][t]));}}return d;}
function positiveDet(xs){let tail=new F(0),det=new F(1);for(let j=xs.length-1;j>=0;j--){const q=F.of(xs[j]),pivot=new F(1).add(q.mul(tail));det=det.mul(pivot.pow(2));tail=s.step(q,tail);}return det;}
check('reject_zero_negative_float_and_empty_couplings',()=>{for(const xs of [[],[0],[-1],[0.1]])assert.throws(()=>s.enclose(xs));assert.throws(()=>s.enclose('3,2'));});
check('reject_negative_tail_and_zero_tolerance',()=>{assert.throws(()=>s.fromTail([1],-1));assert.throws(()=>s.solvePeriodic({tolerance:0}));assert.throws(()=>s.solvePeriodic({maxCells:8193}));});
check('derive_pair_balance_from_both_edge_products',()=>{const b=bondsFor([3,2],1);assert.deepEqual(s.pairedCellsFromBonds(b).map(String),['3','2']);b[1].closing=b[1].closing.mul(2);assert.throws(()=>s.pairedCellsFromBonds(b),/Pair-balance/);assert.throws(()=>s.pairedCellsFromBonds(b.slice(0,3)));});
check('symbolic_native_pair_identities_replay',()=>{for(const [p,q,u,v] of [[3,3,1,'2/3'],['1/2','3/4',1,0],[2,1,2,1],[1,2,'1/2','1/4']]){const w=s.pairWitness(p,q,{u,v}),P=r1.emk();for(const proof of Object.values(w.proofs))assert(P.replay(proof));}results.symbolic_pair_proof_names=['schur','leftInverse','rightInverse','response'];});
check('full_effective_pair_inverses_match_two_channel_formula',()=>{for(const p of ['1/2',1,2,3])for(const q of ['3/4',1,2])for(const v of [0,'1/3',1]){let expected;try{expected=s.pairResponse(p,q,{u:1,v});}catch(e){assert.match(e.message,/Singular/);continue;}
 const tail=add(I(2),scale(L,v)),A=I(4),last=sub(I(2),mul(mul(scale(K,q),tail),R));for(let i=0;i<2;i++)for(let j=0;j<2;j++){A[i][j+2]=scale(K,p)[i][j].neg();A[i+2][j]=R[i][j].neg();A[i+2][j+2]=last[i][j];}const inv=inverse(A);eq(mul(A,inv),I(4));eq(corner(inv),add(scale(I(2),expected.u),scale(L,expected.v)));counts.local_pair_inverses++;}});
check('pair_balance_is_exact_unit_channel_closure_condition',()=>{for(const p of [1,2,3])for(const q of [1,2,3])for(const u of ['1/2',1,2]){const out=s.pairResponse(p,q,{u,v:5});assert.equal(out.unitChannelPreserved,F.of(p).eq(F.of(q).mul(u)));}});
check('mismatch_generates_second_response_coordinate',()=>{const z=s.pairResponse('1/2','3/4');num(z.u,'13/15');num(z.v,'8/15');assert.equal(z.unitChannelPreserved,false);results.mismatch={leftProduct:'1/2',rightProduct:'3/4',identityCoefficient:z.u,KR:z.v};});
check('positive_mismatch_can_make_an_even_aperture_singular',()=>{const b=[{opening:2,closing:1},{opening:1,closing:1}];assert.throws(()=>inverse(fullChain(b)),/Singular/);assert.throws(()=>s.pairResponse(2,1),/Singular/);});
check('paired_elimination_avoids_singular_intermediate_half_step',()=>{assert.throws(()=>inverse(fullChain([{opening:1,closing:1}])),/Singular/);const a=fullChain(bondsFor([1]));eq(corner(inverse(a)),add(I(2),L));});
const profiles=[[1],[3,2],[6,1],['1/2',3,'2/5'],[4,16,36],[1,2,4,8],[3,2,3,2],[2,'1/7','7/3',5],['1/5','1/6','1/7','1/8'],[3,2,5,1,4]];
check('inhomogeneous_finite_apertures_independently_inverted',()=>{for(const xs of profiles)for(const variant of [0,1]){const a=fullChain(bondsFor(xs,variant)),inv=inverse(a),expected=add(I(2),scale(L,s.fromTail(xs)));eq(mul(a,inv),I(a.length));eq(mul(inv,a),I(a.length));eq(corner(inv),expected);assert(determinant(a).eq(new Cut(positiveDet(xs))));counts.direct_full_inverses++;}});
check('directional_amplitude_ratio_is_not_falsely_reconstructed',()=>{eq(corner(inverse(fullChain(bondsFor([3,2],0)))),corner(inverse(fullChain(bondsFor([3,2],1)))));});
check('fixed_prefix_order_is_not_reverse_iteration',()=>{num(s.fromTail([3,2,4]),'9/5');num(s.fromTail([3,2]),'3/7');num(s.fromTail([2,3]),'2/7');assert(!s.fromTail([3,2,4]).eq(s.fromTail([4,2,3])));});
check('unimodular_transfer_and_exact_width_identity',()=>{for(const xs of profiles){const p=s.transfer(xs),e=s.enclose(xs);num(p.A.mul(p.D).sub(p.B.mul(p.C)),xs.length%2?-1:1);num(e.interval.width,new F(1).div(p.C.mul(p.D)));num(e.interval.zeroTail,s.fromTail(xs));}});
check('all_nonnegative_tail_samples_lie_in_certified_interval',()=>{for(const xs of profiles)for(const tail of [0,'1/100',1,2,100,1000000]){const e=s.enclose(xs),x=s.fromTail(xs,tail);assert(e.interval.lower.le(x)&&x.le(e.interval.upper));counts.tail_enclosures++;}});
check('successive_depths_nest_on_one_nonstationary_profile',()=>{const xs=Array.from({length:90},(_,j)=>new F((j*17)%23+1,(j*7)%11+1));let old=s.enclose(xs.slice(0,1));for(let n=2;n<=xs.length;n++){const next=s.enclose(xs.slice(0,n));assert(old.interval.lower.le(next.interval.lower)&&next.interval.upper.le(old.interval.upper));num(next.interval.infiniteTailEndpoint,old.interval.zeroTail);old=next;}});
check('exact_boundary_difference_formula',()=>{for(const xs of profiles){const P=s.transfer(xs);for(const [x,y] of [[0,1],['1/3',2],[5,9]]){const expected=F.of(x).sub(y).abs().div(P.C.mul(x).add(P.D).mul(P.C.mul(y).add(P.D)));num(s.fromTail(xs,x).sub(s.fromTail(xs,y)).abs(),expected);}}});
check('all_bounded_profiles_have_uniform_cutoff_width_bound',()=>{for(const Q of ['1/5',1,3,50])for(let n=1;n<=36;n++){const xs=Array.from({length:n},(_,j)=>F.of(Q).div((j*7)%5+1)),e=s.enclose(xs);assert(e.interval.width.le(F.of(Q).div(Math.ceil(n/2))));}});
check('R2_reduces_exactly_to_homogeneous_R1',()=>{for(const q of ['1/10','1/2','6/5',1,3,10])for(let k=1;k<=20;k++){const e=s.enclose(Array(k).fill(q)),b=r1.bracket(q,k-1);num(e.interval.lower,b.lower);num(e.interval.upper,b.upper);num(e.interval.zeroTail,b.right);}});
check('finite_coupling_cut_is_synthesized_not_assumed',()=>{for(const b of ['1/3',1,2,10]){const design=s.synthesize(1,b);num(design.period[0],F.of(b).add(1));num(s.periodTwoResidual(...design.period,1),0);assert(design.exactNativeCut);num(design.normalizedCutDefect,0);const Q=scale(add(I(2),L),'1/2');eq(mul(Q,Q),Q);const out=s.solvePeriodic({pattern:design.period,tolerance:'1/10000000000'});assert(out.interval.lower.le(1)&&new F(1).le(out.interval.upper));}results.finiteCouplingCut={period:['3','2'],exactReturn:'1',otherDepthReturn:'2/3',fullResponse:'I+KR',normalizedResponse:'(I+KR)/2',finiteCoupling:true,infiniteApertureLimit:true,idempotenceDefect:'0'};});
check('arbitrary_positive_target_return_has_exact_inverse_design',()=>{for(const x of ['1/3','2/3',1,2,'5/2'])for(const b of ['1/2',2,3]){const d=s.synthesize(x,b),out=s.solvePeriodic({pattern:d.period,tolerance:'1/1000000000'});num(s.periodTwoResidual(...d.period,x),0);assert.equal(d.exactNativeCut,F.of(x).eq(1));assert.equal(out.status,'CERTIFIED_RECOGNITION_RESPONSE');assert(out.interval.lower.le(x)&&F.of(x).le(out.interval.upper));counts.periodic_targets++;}});
check('synthesize_entire_periodic_return_profile',()=>{for(const target of [[1,'2/3','1/2'],[1,'1/2','3/2','1/4'],['1/3','1/4'],['1/2']]){const d=s.synthesizePattern(target);for(let j=0;j<target.length;j++){const rotated=d.period.slice(j).concat(d.period.slice(0,j)),r=s.solvePeriodic({pattern:rotated,tolerance:'1/10000000'});assert(r.interval.lower.le(target[j])&&F.of(target[j]).le(r.interval.upper));}}assert.deepEqual(s.synthesizePattern([1,'2/3','1/2']).period.map(String),['3','1','1']);assert.throws(()=>s.synthesizePattern([2,'1/5','3/5']),/periodic wrap/);assert.throws(()=>s.synthesizePattern([1,1]));results.profileSynthesis={target:['1','2/3','1/2'],designedCells:['3','1','1'],nativeCutAtPhase:0,condition:'a_j=x_j/(1-x_j*x_(j+1)), with cyclic adjacent products <1'};});
check('increasing_coupling_can_move_off_the_exact_cut',()=>{num(s.periodTwoResidual(3,2,1),0);num(s.periodTwoResidual(30,20,'6/5'),0);num(new F(6,5).pow(2).sub(1).div(4),'11/100');results.strengthAlone={periodAtCut:[3,2],scaledPeriod:[30,20],scaledResponse:'6/5',scaledCutDefect:'11/100'};});
check('main_periodic_cut_enclosure_is_independent_of_exact_root',()=>{const out=s.solvePeriodic();assert.equal(out.status,'CERTIFIED_RECOGNITION_RESPONSE');assert(out.interval.midpoint.sub(1).abs().le(out.interval.error));assert(out.interval.error.le('1/1000000000000'));results.main={pattern:out.input.pattern,cellsUsed:out.cellsUsed,apertureHeight:out.apertureHeight,responseError:out.interval.error,normalizedCutError:out.interval.error.div(2),exactResponse:'I+KR'};});
check('periodic_boundary_coefficients_match_direct_native_powers',()=>{let coefficientChecks=0;for(const [a,b] of [[3,2],[6,1],[2,3]]){const xs=Array.from({length:6},(_,j)=>j%2?b:a),A=fullChain(bondsFor(xs)),H=sub(I(A.length),A);let state=Z(A.length,2);state[0][0]=ONE;state[1][1]=ONE;for(let k=0;k<=22;k++){let expected=Z(2);if(k===0)expected=I(2);else if(k%2===0){const n=k/2;if(n%2){const m=(n-1)/2,coefficient=r1.catalan(m).mul(new F(a).pow(m+1)).mul(new F(b).pow(m)).mul(m%2?-1:1);expected=scale(L,coefficient);}}eq(corner(state),expected);if(k<=12)eq(state.slice(2*k,2*k+2),scale(o.power(R,k),new F(2).pow(k)));state=mul(H,state);coefficientChecks++;}}results.periodicMoments={directChecks:coefficientChecks,mainOddCoefficients:['3','-18','216','-3240'],radiusInPairCounter:'1/(2*sqrt(6))',atOne:'DIVERGENT',fullUncutTermLowerBound:'2^n'};});
check('finite_coupling_cut_outside_its_own_return_series_radius',()=>{let last=new F(0);for(let m=0;m<=12;m++){const term=r1.catalan(m).mul(new F(3).pow(m+1)).mul(new F(2).pow(m));assert(last.le(term));if(m>0)assert(new F(6).mul(last).le(term));last=term;}assert(new F(1000000).le(last));});
check('same_period_product_different_readouts_and_cut_status',()=>{const a=s.synthesize(1,2),b=s.synthesize(2,1);num(a.period[0].mul(a.period[1]),b.period[0].mul(b.period[1]));assert(a.exactNativeCut&&!b.exactNativeCut);num(b.normalizedCutDefect,'3/4');num(s.periodTwoResidual(2,3,'2/3'),0);results.sameScalarPeriodProduct={first:[3,2],second:[6,1],product:6,returns:['1','2'],cutDefects:['0','3/4'],shiftedFirstPeriod:[2,3],shiftedReturn:'2/3'};});
check('persistent_bulk_asymmetry_does_not_select_R1_cut',()=>{for(const g of [10,100,1000]){assert(s.periodTwoResidual(6*g,g,'12/5').n<=0n);assert(s.periodTwoResidual(6*g,g,'5/2').n>0n);}results.bulkAsymmetry={profile:'g*(6,1,6,1,...)',strongReturnLimit:'sqrt(6)',normalizedIdempotenceDefectLimit:'5/4',universalCutSelection:false};});
check('finite_defects_preserve_the_balanced_strong_return_limit',()=>{let last=null;for(const d of ['1/2','2/3','4/5','9/10','99/100']){const t=F.of(d),q=t.div(new F(1).sub(t.pow(2))),ratios=['1/2',3,'2/3'],actual=s.fromTail(ratios.map(x=>q.mul(x)),t),depth=20+Number((20n*q.n+q.d-1n)/q.d),e=s.balancedDefectEnclosure(ratios,q,depth);assert(e.lower.le(actual)&&actual.le(e.upper));assert(actual.sub(1).abs().div(2).le(e.cut_error_bound));last=e.cut_error_bound;}assert(last.le('1/25'));results.finiteDefects={ratios:['1/2','3','2/3'],theorem:'Every fixed finite positive defect prefix over a homogeneous strong-return tail tends to the same native cut',lastTestBound:rounded(last),reportBoundRoundedOutward:true,cutoffGrowsWithCoupling:true};});
check('finite_data_does_not_claim_an_unknown_infinite_profile_converges',()=>{assert.match(s.enclose([1,2,3]).scope,/does not infer/);const out=s.solvePeriodic({pattern:[100],maxCells:2,tolerance:'1/1000000000000'});assert.equal(out.status,'REFINEMENT_BUDGET_EXHAUSTED');assert(!out.global_inverse_claimed);});
check('normalized_denominator_products_follow_exact_increment_law',()=>{const xs=Array.from({length:40},(_,j)=>new F((j+1)*(j+2),3));let prev=s.transfer(xs.slice(0,1));for(let n=2;n<=xs.length;n++){const next=s.transfer(xs.slice(0,n));num(next.C.mul(next.D).sub(prev.C.mul(prev.D)),prev.D.pow(2).div(xs[n-1]));prev=next;}});
check('square_profile_keeps_boundary_interval_width_at_every_tested_depth',()=>{for(let n=1;n<=80;n++){const out=s.persistentSquareWitness(n);assert(new F(1,4).le(out.interval.width));const diff=s.fromTail(out.cells,0).sub(s.fromTail(out.cells,1)).abs();assert(new F(1,8).le(diff));}const out=s.persistentSquareWitness(40);results.persistentBoundary={profile:out.infinite_profile,reciprocalSumUpperBound:out.reciprocal_sum_upper_bound,widthLowerBoundAllDepths:out.all_depths_width_lower_bound,zeroVersusOneTailSeparationLowerBound:'1/8',depth40Lower:rounded(out.interval.lower,false),depth40Upper:rounded(out.interval.upper),reportEndpointsRoundedOutward:true,allFiniteAperturesInvertible:true,oneLimitClaimed:false};});
check('harmonic_profile_has_explicit_divergent_reciprocal_budget',()=>{for(let m=1;m<=9;m++){const start=2**m,end=2**(m+1);let total=new F(0);for(let j=start;j<end;j++)total=total.add(new F(1,4*j));assert(new F(1,8).le(total));}results.harmonicProfile={profile:'a_j=4(j+1)',eachDyadicReciprocalBlockAtLeast:'1/8',boundaryIndependentLimit:'PROVED_BY_DIVERGENT_RECIPROCAL_SUM_NOT_BY_FINITE_SAMPLING'};});
check('two_channel_local_readout_recovers_both_edge_products',()=>{for(const [p,q,x] of [['1/2','3/4',0],[3,3,'2/3'],[2,3,2],[1,2,1]]){const r=s.pairResponse(p,q,{u:1,v:x}),recovered=s.recoverProducts(r.u,r.v,x);num(recovered.leftProduct,p);num(recovered.rightProduct,q);assert(!recovered.individual_directional_amplitudes_recovered);}assert.throws(()=>s.recoverProducts(1,0));});
check('proof_replay_refuses_changed_presentation_hash',()=>{const w=s.pairWitness(3,3,{u:1,v:'2/3'}),bad=JSON.parse(JSON.stringify(w.proofs.schur));bad.presentation='substituted';assert.throws(()=>r1.emk().replay(bad));});
check('new_solver_still_uses_exact_cut_field',()=>{assert.throws(()=>s.synthesize(0.1,2));assert.throws(()=>s.pairResponse(1,2,{u:1,v:0.5}));});
const binding=['variable_return.cjs','verify.cjs','mutate.cjs','THEOREM.md','README.md','LINEAGE.json','../return_solver.cjs','../../../operator_foundation/core/native_operator.cjs','../../../operator_foundation/core/paninian_operator.cjs'];
if(process.argv.includes('--assert-only')){console.log(JSON.stringify({status:'PASS_MATHEMATICAL_ASSERTIONS',check_count:checks.length,counts},null,2));process.exit(0);}
const sha=x=>crypto.createHash('sha256').update(x).digest('hex'),source_sha256=Object.fromEntries(binding.map(f=>[f,sha(fs.readFileSync(path.join(__dirname,f)))]));
const report={protocol:'RKF_NONSTATIONARY_GRADED_APERTURE_R2',status:'PASS_EXACT_FINITE_CHECKS',runtime:process.version,check_count:checks.length,checks,counts,results,source_sha256,scope:{native_hilbert_primitive:false,positive_pairing_primitive:false,operator_family:'positive depth-varying pair-balanced EMK excursion family; local mismatch formula also specified',convergence_theorem:'boundary independence iff sum_j 1/a_j diverges',general_proofs:'THEOREM.md; finite tests do not prove infinite statements',external_priority_established:false,infinite_full_operator_inverse_claimed:false,physical_quantum_gravity_claimed:false,historical_science_suites_rerun:false}};
const text=JSON.stringify(report,null,2)+'\n',hash=sha(text),file=path.join(__dirname,'RESULT.json'),pin=path.join(__dirname,'EXPECTED.sha256');if(process.argv.includes('--write')){fs.writeFileSync(file,text);fs.writeFileSync(pin,hash+'\n');}else if(process.argv.includes('--check')){assert.equal(fs.readFileSync(file,'utf8'),text,'Source/evidence drift');assert.equal(fs.readFileSync(pin,'utf8').trim(),hash,'Pin mismatch');}
console.log(JSON.stringify({status:report.status,check_count:checks.length,counts,main:results.main,certificate_sha256:hash},null,2));
